### PR TITLE
New data table from MarkSwinbank

### PR DESCRIPTION
**Pull request by SirArthurTheSubmitter**
Data table added by MarkSwinbank at 2015-05-26T13_27_31.183199

### CODE REVIEW

**Comment by keflavich** [comment]
@snlongmore looks like it worked this time

**Comment by snlongmore** [comment]
Looks like it worked well. Funny thing that it deletes the final line of the existing file and then puts it back in again... @keflavich is this a known "feature"?

**Comment by keflavich** [comment]
it looks like a bug related to having a newline at the end of the file.  too minor to concern ourselves with now.

**Comment by snlongmore** [comment]
Thanks. OK, lets ignore it!

**Pull request merged**
