### PR TITLE
New data table from GinaSantangelo

### PR DESCRIPTION
**Pull request by SirArthurTheSubmitter**
Data table added by GinaSantangelo at 2015-06-16T11_04_25.490043

### CODE REVIEW

**Comment by ltesti** [comment]
Test do not merge

**Comment by keflavich** [comment]
@ltesti - can you close and delete this or others?  You should see something that looks like this:

image

if so.  If not, just tell me and I'll close/delete or merge for you.

**Comment by ltesti** [comment]
@keflavich this is what I see:
screen shot 2015-06-17 at 13 54 11

**Comment by ltesti** [comment]
@keflavich probably it will be good to add me as a possible contributor (I promise to avoid erasing everything or insert random bugs in somebody else code...)

**Comment by keflavich** [comment]
@ltesti - I added you

**Pull request closed without merging**
